ORS_API_KEY = "eyJvcmciOiI1YjNjZTM1OTc4NTExMTAwMDFjZjYyNDgiLCJpZCI6ImEwNjFjNmNhZmJiNTQ5OTI5Y2UwNmU2MzdjOTY2MGFjIiwiaCI6Im11cm11cjY0In0="
GEMINI_API_KEY = "AIzaSyBk7NRrP1ewUteOBD6b3JGEdZ5RSAUowlE"
AI_PASSWORD = "rfm"